sudo: false
language: node_js
node_js:
  - "6"
  - "7"
  - "8"
script:
  - npm run clean
  - npm run build
  - npm run lint
branches:
  only:
    - master
    - dev
cache:
  directories:
    - node_modules
